SELECT DISTINCT product_category,
SUM(PRODUCT_ID) AS Total_Number_Of_Id_Per_Cartegory, 
COUNT (PRODUCT_TYPE) AS Product_available, 
SUM (TRANSACTION_QTY) AS Total_Transaction_Quantity, 
SUM (UNIT_PRICE) AS Total_amount_Purchase_Per_Cartegory, 
COUNT(PRODUCT_CATEGORY) AS Total_Number_Of_Cartegoty, 
COUNT(PRODUCT_CATEGORY) AS Total_Number_Of_Cartegoty, 
COUNT(TRANSACTION_TIME) AS Total_Number_Purchase, 
DAYNAME (TRANSACTION_DATE) AS Day_of_Transaction, 
TO_DATE (TRANSACTION_DATE) AS Purchase_Date,

CASE
  WHEN TRANSACTION_DATE BETWEEN '2023-01-01' AND '2023-01-30' THEN 'January' 
  WHEN TRANSACTION_DATE BETWEEN '2023-02-01' AND '2023-02-28' THEN 'February' 
  WHEN TRANSACTION_DATE BETWEEN '2023-03-01' AND '2023-03-30' THEN 'March' 
  WHEN TRANSACTION_DATE BETWEEN '2023-04-01' AND '2023-04-30' THEN 'April' 
  WHEN TRANSACTION_DATE BETWEEN '2023-05-01' AND '2023-05-30' THEN 'May' 
ELSE 'June' 
END AS Transaction_By_Month,

CASE
  WHEN TRANSACTION_TIME BETWEEN '07:00:00' AND '11:59:00' THEN 'Morning'
  WHEN TRANSACTION_TIME BETWEEN '12:00:00' AND '16:59:00' THEN 'Afternoon' 
ELSE 'Evening' 
END Day_time 
FROM COFFEE.PUBLIC.SHOP

GROUP BY ALL;
